### ISSUE TITLE
Suggestions for Command Line Page

### ISSUE THREAD

**Issue by kylr1516** [byu-cpe/ecen224#11]
it needs to be clearer that this lab should be done on the Pi especially the part with the challenge. Also it should be made clearer that the challenge is mandatory and an addition to the reamed would most likely help with this. Also, the part about alias should probably be revised so that it tells people to add it rather than change it since I and others didn't have any already in our .zshrc file.

**Comment by christopolise** [comment]
All of this has been addressed in the new update. Thanks!
