### ISSUE TITLE
Suggestions for Image Page

### ISSUE THREAD

**Issue by Virginia2244** [byu-cpe/ecen224#14]
grammar

> In this lab we be exploring the utility of data manipulation in a practical by editing an image in C.

should be

> In this lab we **will** be exploring the utility of data manipulation in a practical **application** by editing an image in C.

**Comment by Virginia2244** [comment]
Also
> In this lab we be exploring the utility of data manipulation in a practical by editing an image in C.

To

>In this lab we will be exploring the utility of data manipulation in a practical application by editing an image in C.

**Comment by philipbl** [comment]
Fixed. Thanks!
