### ISSUE TITLE
Suggestions for Image Page

### ISSUE THREAD

**Issue by EpicPantalones** [byu-cpe/ecen224#15]
Under the "Pixel Values in BMP File" section:

"Specifically in the BMP file, the values begin from the bottom left and fill up the row right to left and fill up the screen bottom to top."

If it starts in the bottom left, how can it be going right to left? I think that this sentence is a bit misleading. Does it go left to right from the bottom left? Or is it going right to left and it meant to say from the bottom right?

**Comment by philipbl** [comment]
Thanks!
