### ISSUE TITLE
Your binary must output to a folder called `bin`.

### ISSUE THREAD

**Issue by jgoeders** [byu-cpe/ecen224#30]
https://github.com/byu-cpe/ecen224/blob/508f49421b722e95d2ebbd93ebf2f9f114571603/_labs/display.md?plain=1#L183

# - Your binary must output to a folder called `bin`. This folder will be marked to be ignored by `git`, meaning that I will not receive your final compiled binary to test, but rather your code which must compile successfully on my Pi Z2W. 

I don't understand this.  Why do you care where they compile their binary?  The current .gitignore doesn't include a bin folder, so even if they put it in a bin folder, it may still end up in git.

Isn't it enough to just say "Do not commit your compiled binary to git.  If you do, it will be ignored during grading.  When grading, I will compile your code, which must compile successfully on my Pi Z2W"

**Comment by philipbl** [comment]
We have removed that from the lab.
