### ISSUE TITLE
Suggestions for Lab Setup Page

### ISSUE THREAD

**Issue by Virginia2244** [byu-cpe/ecen224#5]
After this line

> Once you have accepted the assignment, a copy of the lab repository will be added to the GitHub user account you are using for this class. To clone these files, or download them to your computer (or for this lab, to the Pi Z2W), you will need to need the repository link. This is different than the URL of your repository.

A screenshot of a repository with the thing we are supposed to be copying may be helpfull

**Comment by christopolise** [comment]
Screenshot has been added
