### ISSUE TITLE
Suggestions for Command Line Page

### ISSUE THREAD

**Issue by pfeif11001** [byu-cpe/ecen224#58]
This challenge is quite ambiguous and all over the place. I understand that the point is to explore the directories with different commands, but it might be good to include a way to know if you completed each step and if you're going in the right order.
For example, the first folder in the list said:
"echo "Congratulations! You have almost reached the end of the challenge! For the last task, install the package called tree and use it at the top of the folders for this challenge. Make sure that tree shows ALL of the files and folders, including the hidden ones. Save the output of this command to a file called tree.txt"

**Comment by philipbl** [comment]
We tried to fix this in the Winter 2024 semester.
