### ISSUE TITLE
Suggestions for Image Page

### ISSUE THREAD

**Issue by EpicPantalones** [byu-cpe/ecen224#61]
There is an unfinished sentence:
"Look at the pxl_data field in the Bitmap struct shown above. What type does it use? (Feel free to ignore the star). While creating the algorithms below, keep in mind that the values are stored as colors and NOT pixels. For example, if you want to access the blue color for two pixels"

**Comment by EpicPantalones** [comment]
This comes a few lines above the Requirements Header in the section about how images are stored as pixel data

**Comment by philipbl** [comment]
Thanks! I was half asleep when I did this 😴
